//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouTubeFavorites.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JimKelleher")]
        public string YOUTUBE_ACCOUNT_CHANNEL {
            get {
                return ((string)(this["YOUTUBE_ACCOUNT_CHANNEL"]));
            }
            set {
                this["YOUTUBE_ACCOUNT_CHANNEL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jim_kelleher@comcast.net")]
        public string YOUTUBE_ACCOUNT_USER_NAME {
            get {
                return ((string)(this["YOUTUBE_ACCOUNT_USER_NAME"]));
            }
            set {
                this["YOUTUBE_ACCOUNT_USER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("medford2517")]
        public string YOUTUBE_ACCOUNT_PASSWORD {
            get {
                return ((string)(this["YOUTUBE_ACCOUNT_PASSWORD"]));
            }
            set {
                this["YOUTUBE_ACCOUNT_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kelleher.db.6699012.hostedresource.com;Initial Catalog=kelleher;Persi" +
            "st Security Info=True;User ID=kelleher;Password=F5#mUnKX")]
        public string DATABASE_CONNECTION_STRING {
            get {
                return ((string)(this["DATABASE_CONNECTION_STRING"]));
            }
            set {
                this["DATABASE_CONNECTION_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2530/Default.aspx/")]
        public string RUN_URL_PREFIX_DEV {
            get {
                return ((string)(this["RUN_URL_PREFIX_DEV"]));
            }
            set {
                this["RUN_URL_PREFIX_DEV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.workingweb.info/JimRadio/")]
        public string RUN_URL_PREFIX_PROD {
            get {
                return ((string)(this["RUN_URL_PREFIX_PROD"]));
            }
            set {
                this["RUN_URL_PREFIX_PROD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome")]
        public string BROWSER_CHROME {
            get {
                return ((string)(this["BROWSER_CHROME"]));
            }
            set {
                this["BROWSER_CHROME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("firefox")]
        public string BROWSER_FIREFOX {
            get {
                return ((string)(this["BROWSER_FIREFOX"]));
            }
            set {
                this["BROWSER_FIREFOX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iexplore")]
        public string BROWSER_INTERNET_EXPLORER {
            get {
                return ((string)(this["BROWSER_INTERNET_EXPLORER"]));
            }
            set {
                this["BROWSER_INTERNET_EXPLORER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("safari")]
        public string BROWSER_SAFARI {
            get {
                return ((string)(this["BROWSER_SAFARI"]));
            }
            set {
                this["BROWSER_SAFARI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opera")]
        public string BROWSER_OPERA {
            get {
                return ((string)(this["BROWSER_OPERA"]));
            }
            set {
                this["BROWSER_OPERA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyD19DQuEq9Jc_R75eyOZdLi2qzmmQqG6ss")]
        public string YOUTUBE_API_BROWSER_KEY {
            get {
                return ((string)(this["YOUTUBE_API_BROWSER_KEY"]));
            }
            set {
                this["YOUTUBE_API_BROWSER_KEY"] = value;
            }
        }
    }
}
